### ISSUE TITLE
Can netmaster be run in a container?

### ISSUE THREAD

**Issue by flightpath** [contiv/netplugin#227]
Is it possible to run netmaster and netplugin in a container?

**Comment by jainvipin** [comment]
@flightpath - I am curious if there is a reason you prefer running it as a container instead of systemctl service. While the advantages of running it as a container are clear, there are some disadvantages too:
- systemctl provides a good dependency graph of services e.g.. netmaster depending on etcd
- accidental removal wouldn't happen with systemctl services e.g. docker rm -f $(docker ps -aq) could remove netmaster and netplugin containers too
- with system-ctl auto-restarting a servcie is built into the OS, however I am not sure if docker would restart containers upon a node reboot.

Would love to get your take on these issues...

**Comment by mapuri** [comment]
@flightpath 
yes it should be possible to run them in containers but we have not tested that yet. netplugin requires access to ovs kernel data path so it will mostly be need to be run as a privileged/system container and the host os will need to have ovs kernel modules installed.

@jainvipin 
Running a container as a systemd unit is possible, so we shall be able to use systemd for running netmaster/netpugin in containers.

**Comment by jainvipin** [comment]
> Running a container as a systemd unit is possible, so we shall be able to use systemd for running netmaster/netpugin in containers.

good point; however other concerns like accidental removal of container is still an issue.

**Comment by abhinandanpb** [comment]
netmaster and netplugin has been containerized.
